[versions]

# Android constants
android-minSdk = "24"
android-compileSdk = "35"
android-targetSdk = "35"

# Core
kotlin = "2.1.0"
compose = "1.8.1"
compose-plugin = "1.8.1"
agp = "8.9.2"

# AndroidX
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-core-ktx = "1.16.0"
androidx-material = "1.12.0"
androidx-preferences = "1.2.1"
androidx-test-junit = "1.1.5"

# Ark
decompose = "3.4.0-alpha02"
mviKotlin = "4.3.0"
essenty = "2.5.0"

# Libs
detekt = "1.23.5"
kotlinx-coroutines = "1.9.0"
kotlinx-serialization = "1.6.3"
kotlinx-datetime = "0.6.1"
multiplatformSettings = "1.3.0"
napier = "2.7.1"
ktor = "3.0.3"
sqlDelight = "2.0.2"
oidc = "0.12.1"
imageLoader = "1.10.0"
fileKit = "0.8.8"
okio = "3.10.2"
blurhash = "0.3.0"
ksoup = "0.5.0"

# Testing
assertk = "0.28.1"
kover = "0.8.1"
mokkery = "2.6.1"

[libraries]

kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "org.jetbrains.compose.gradle.plugin", version.ref = "compose-plugin" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-preferences = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preferences" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-desktop = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }

ark-mvikotlin-core = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mviKotlin" }
ark-mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mviKotlin" }
ark-mvikotlin-extensions = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mviKotlin" }
ark-decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
ark-decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
ark-essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

lib-napier = { module = "io.github.aakira:napier", version.ref = "napier" }
lib-imageLoader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }
lib-fileKit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "fileKit" }
lib-fileKit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "fileKit" }
lib-settings-core = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
lib-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatformSettings" }
lib-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
lib-blurhash = { module = "com.vanniktech:blurhash", version.ref = "blurhash" }
lib-ksoup = { group = "com.mohamedrejeb.ksoup", name = "ksoup-html", version.ref = "ksoup" }

lib-sqlDelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
lib-sqlDelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
lib-sqlDelight-driver-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
lib-sqlDelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }

oidc-appsupport = { module = "io.github.kalinjul.kotlin.multiplatform:oidc-appsupport", version.ref = "oidc" }
oidc-okhttp4 = { module = "io.github.kalinjul.kotlin.multiplatform:oidc-okhttp4", version.ref = "oidc" }
oidc-ktor = { module = "io.github.kalinjul.kotlin.multiplatform:oidc-ktor", version.ref = "oidc" }

test-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
mokkery-coroutines = { module = "dev.mokkery:mokkery-coroutines", version.ref = "mokkery" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
